Implement tag renaming
burtonator/polar-bookshelf pull request #1610
Opened 2021-04-14 23:39 UTC by WinterCore

Changelog:

2021-04-19 14:19 UTC, burtonator requested changes
Just a few small changes

2021-04-19 16:56 UTC, burtonator commented on apps/repository/js/persistence_layer/PersistenceLayerMutator2.tsx
> +        // FIXME REVIEW: I was thinking of creating a union type for these 4 ITextHighlight | IAreaHighlight | IFlashcard | IComment
I'm fine with that... go for it... something like IAnnotationType or something?

2021-04-19 16:57 UTC, burtonator commented on apps/repository/js/persistence_layer/PersistenceLayerMutator2.tsx
> +        // FIXME REVIEW: I was hoping to share some code between prepare & commit but I wasn't able to
OK... I'll yield to you on this. I don't think it's a problem if refactoring would take a significant amount of time.

2021-04-19 17:06 UTC, WinterCore commented on apps/repository/js/persistence_layer/PersistenceLayerApp.tsx
> +        <PersistenceContext.Provider value={persistenceContext}>
Yes

2021-04-20 02:39 UTC, burtonator approved these changes

2021-04-20 02:39 UTC, merged